spring:
  application:
    name: PhotoAppApiConfigServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:D:\1_BE\Java\microservice\MyLearn\PhotoAppApiConfigServer
        git:
          uri: https://github.com/thucpug/PhotoAppApiConfigServer
          username: thucpug
          password: thuc0533
          clone-on-start: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
server:
  port: 8012
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
