server:
  port: 0
spring:
  devtools:
    restart:
      enabled: true
  application:
    name: UserManagement
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka