eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8000
spring:
  application:
    name: discoveryservice
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672